require('dotenv').config();

const transporter = require('../config/mail');

function generateEmailHtml({ from, subject, message }) {
    return `
<div style="font-family: arial; width: 100%">
<header style="padding: 1.5rem; background: linear-gradient(90deg, #D94B8B, #8B6CC6); color: white; text-align: center">
<h1 style="margin-bottom: 12px">Iwan Portfolio</h1>
<p style="margin-top: 0">Contact Notification</p>
</header>
<main style="padding: 1.5rem; line-height: 1.5rem">
<p>Hello, Iwan!</p>
<p>There's a message for you! they contacted you via the contact form in your portfolio website, check it out! details are as follows.</p>
<table style="width: 100%; border: 1px solid gray; border-collapse: collapse;">
	<tr>
    	<th style="border: 1px solid gray; padding: 0.5rem; text-align: left;">From</th>
        <td style="border: 1px solid gray;; padding: 0.5rem">${from}</td>
    </tr>
	<tr>
    	<th style="border: 1px solid gray; padding: 0.5rem; text-align: left;">Subject</th>
        <td style="border: 1px solid gray; padding: 0.5rem">${subject}</td>
    </tr>
	<tr>
    	<th style="border: 1px solid gray; padding: 0.5rem; text-align: left;">Message</th>
        <td style="border: 1px solid gray; padding: 0.5rem">${message}</td>
    </tr>
</table>

<p>Keep it up the good work, Iwan!</p>

<p>Warm regards<br>
<em>Your kindest self</em></p>
</main>
<footer style="padding: 1rem; background: linear-gradient(90deg, #D94B8B, #8B6CC6); color: white; text-align: center">
<p style="margin: 0">Automatically Generated by Iwan Portfolio</p>
</footer>
</div>
`;
}

module.exports = async function sendFeedback({ from, subject, message }) {
    await transporter.sendMail({
        from: from,
        to: process.env.EMAIL_TO,
        subject: 'CONTACT NOTIFICATION | Iwan Portfolio',
        html: generateEmailHtml({ from, subject, message })
    });
}